[tool.poetry]
name = "anacondaworkshop01"
version = "0.1.0"
description = ""
authors = ["Erico Djasmeini <ericodjasmeini@gic.com.sg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
